[build]
  command = "hugo"
  publish = "public"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat" # fallback when Edge is unavailable
  status = 200

[[edge_functions]]
  path = "/api/chat"
  function = "chat-edge"


[build.environment]
  NODE_VERSION = "20"
