[build]
  command = "hugo --gc --minify"
  publish = "public"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat" # fallback when Edge is unavailable
  status = 200

[[edge_functions]]
  path = "/api/chat"
  function = "chat-edge"


[build.environment]
  NODE_VERSION = "20"

[context.production]
  command = "hugo --gc --minify -b $URL"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
